title: Helloheims World
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 This is where I show what I can do!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  helloheim # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
